version: '3'

services:

  master:
    container_name: master
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./static:/usr/local/apache2/htdocs
    depends_on:
      - graphql
      - image-server
    links:
      - graphql

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./logs/:/var/www/data/log
      - ./server:/var/www
      - /var/www/vendor # https://blog.codeship.com/using-docker-compose-for-php-development/
    depends_on:
      - database
      - search-api
      - cache-api
    links:
      - database
      - cache-api
      - search-api
    ports:
      - 8080:80
    expose:
      - 8080
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=althingi
      - DB_USER=root
      - DB_PASSWORD=example

      - CACHE_HOST=cache-api
      - CACHE_PORT=6379
      - CACHE_TYPE=memory

      - SEARCH=elasticsearch

      - ES_HOST=search-api
      - ES_PROTO=http
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASSWORD=changeme

      - LOG_PATH=/var/www/data/log/api.log
      - LOG_FORMAT=logstash

  search-api:
    container_name: search-api
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/search-api/:/usr/share/elasticsearch/data

  database:
    container_name: database
    image: mysql:5.6.41
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./server/auto/db/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=example

  cache-api:
    container_name: cache-api
    image: redis:4.0.11
    volumes:
      - ./data/cache-api:/data

  cache-consumer:
    container_name: cache-concumer
    image: redis:4.0.11
    volumes:
      - ./data/cache-consumer:/data

  cache-provider:
    container_name: cache-provider
    image: redis:4.0.11
    volumes:
      - ./data/cache-provider:/data

  graphql:
    container_name: graphql
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - GRAPHQL_SERVER=/graphql
    environment:
      - CLIENT_HOST=api
      - CLIENT_PORT=80
      - IMAGE_SERVER=/images
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - api
    links:
      - api

  aggregator:
    container_name: aggregator
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    volumes:
      - ./logs/:/usr/src/data/log/
    environment:
      - AGGREGATOR_CONSUMER=http://api:80

      - PROVIDER_CACHE_TYPE=memory # memory | file | none
      - PROVIDER_CACHE=true # true | false
      - PROVIDER_CACHE_HOST=cache-provider
      - PROVIDER_CACHE_PORT=6379

      - CONSUMER_CACHE_TYPE=memory # memory | file | none
      - CONSUMER_CACHE=false # true # true | false
      - CONSUMER_CACHE_HOST=cache-consumer
      - CONSUMER_CACHE_PORT=6379

      - LOG_PATH=/usr/src/data/log/aggregator.log
      - LOG_FORMAT=logstash
    depends_on:
      - api
      - cache-consumer
      - cache-provider
    links:
      - api
      - cache-consumer
      - cache-provider
    # command: bash -c "php ./index.php load:assembly && php ./index.php load:party && php ./index.php load:constituency && php ./index.php load:committee && php ./index.php load:category && php ./index.php load:congressman && php ./index.php load:president"
    # command: bash -c "php ./index.php load:congressman --assembly=148 && php ./index.php load:plenary --assembly=148 && php ./index.php load:issue --assembly=148 && php ./index.php load:committee-assembly --assembly=148"
    command: bash -c "./assembly.sh 148"

  image-server:
    container_name: images
    image: apsl/thumbor:6.4.2-simd-avx2
    ports:
      - 8000:8000
    environment:
      - DETECTORS=['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']
    volumes:
      - ./data/thumbor:/data

