version: '3.4'

services:

  master:
    container_name: master
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./static:/usr/local/apache2/htdocs
      - ./logs:/var/logs
    depends_on:
      - graphql
      - image-server
      - logstash
    links:
      - graphql
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "apache"

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./logs/:/var/www/data/log
      - ./server/auto/:/var/www/auto
      - ./server/config/:/var/www/config
      - ./server/module/:/var/www/module
      - ./server/public/:/var/www/public
    depends_on:
      - database
      - search-api
      - cache-api
      - queue
      - accumulator
      - acc-database
    links:
      - database
      - cache-api
      - search-api
      - queue
      - accumulator
      - acc-database
    ports:
      - 8080:80
    expose:
      - 8080
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=althingi
      - DB_USER=root
      - DB_PASSWORD=example

      - CACHE_HOST=cache-api
      - CACHE_PORT=6379
      # - CACHE_TYPE=none
      - CACHE_TYPE=memory

      - SEARCH=elasticsearch

      - ES_HOST=search-api
      - ES_PROTO=http
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASSWORD=changeme

      # - LOG_PATH=/var/www/data/log/api.log
      - LOG_PATH=php://stdout
      - LOG_FORMAT=line

      # - QUEUE=RabbitMQ
      - QUEUE=none
      - QUEUE_HOST=queue
      - QUEUE_PORT=5672
      - QUEUE_USER=admin
      - QUEUE_PASSWORD=Admin@123
      - QUEUE_VHOST=/
      - QUEUE_FORCED=true

      - STORAGE_HOST=acc-database
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "api"

  search-api:
    container_name: search-api
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/search-api/:/usr/share/elasticsearch/data

  database:
    container_name: database
    image: mysql:5.6.41
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 4406:3306
    expose:
      - 4406
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./server/auto/db/:/docker-entrypoint-initdb.d
      - ./server/assets/database/:/home
      - ./assets/database:/etc/mysql/conf.d
      - ./logs/:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "mysql"

  cache-api:
    container_name: cache-api
    image: redis:4.0.11
    # ports:
    #   - 6379:6379
    #   - 63791:6379
    # expose:
    #   - 63791
    volumes:
      - ./data/cache-api:/data

  cache-consumer:
    container_name: cache-concumer
    image: redis:4.0.11
    # ports:
    #   - 6379:6379
    #   - 63792:6379
    # expose:
    #   - 63792
    volumes:
      - ./data/cache-consumer:/data

  cache-provider:
    container_name: cache-provider
    image: redis:4.0.11
    volumes:
      - ./data/cache-provider:/data

  graphql:
    container_name: graphql
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - GRAPHQL_SERVER=/graphql
    environment:
      - CLIENT_HOST=api
      - CLIENT_PORT=80
      - IMAGE_SERVER=/images
    volumes:
      - ./logs/:/home/node/app/logs
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - api
    links:
      - api
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "graphql"

  graphql-dev:
    container_name: graphql-dev
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - GRAPHQL_SERVER=/graphql
    environment:
      - CLIENT_HOST=api
      - CLIENT_PORT=80
      - IMAGE_SERVER=/images
    command: npm run dev
    volumes:
      - ./logs/:/home/node/app/logs
      - ./client/src/:/home/node/app/src
      - ./client/@types/:/home/node/app/@types
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - api
    links:
      - api

  aggregator:
    container_name: aggregator
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    volumes:
      - ./aggregator/auto/:/usr/src/auto
      - ./aggregator/config/:/usr/src/config
      - ./aggregator/module/:/usr/src/module
      - ./aggregator/public/:/usr/src/public
      - ./logs/:/usr/src/data/log/
    environment:
      - AGGREGATOR_CONSUMER=http://api:80

      - PROVIDER_CACHE_TYPE=memory # memory | file | none
      - PROVIDER_CACHE=true # true | false
      - PROVIDER_CACHE_HOST=cache-provider
      - PROVIDER_CACHE_PORT=6379

      - CONSUMER_CACHE_TYPE=memory # memory | file | none
      # - CONSUMER_CACHE_TYPE=none
      - CONSUMER_CACHE=true # true # true | false
      - CONSUMER_CACHE_HOST=cache-consumer
      - CONSUMER_CACHE_PORT=6379

      # - LOG_PATH=/usr/src/data/log/aggregator.log
      - LOG_PATH=php://stdout
      - LOG_FORMAT=line
    depends_on:
      - api
      - cache-consumer
      - cache-provider
    links:
      - api
      - cache-consumer
      - cache-provider
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "aggregator"

  image-server:
    container_name: images
    image: apsl/thumbor:6.4.2-simd-avx2
    ports:
      - 8000:8000
    environment:
      - DETECTORS=['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']
    volumes:
      - ./data/thumbor:/data

  kibana:
    container_name: kibana
    image: kibana:6.7.0
    links:
      - elasticsearch
    ports:
      - '5601:5601'

  logstash:
    container_name: logstash
    build:
      context: ./log-server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:12201:12201/udp"
    links:
      - elasticsearch
    depends_on:
      - kibana
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.7.0

  queue:
    container_name: queue
    image: rabbitmq:3.7.13-rc.2-management
    hostname: rabbit1
    environment:
      - RABBITMQ_ERLANG_COOKIE="jasdfg87asdv8cxv6DUv"
      - RABBITMQ_NODENAME=rabbit1
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Admin@123
    ports:
      # - 4369:4369
      # - 5671:5671
      - 5672:5672
      # - 15671:15671
      - 15672:15672
      # - 25672:25672
    volumes:
      - ./accumulator/assets/definitions.json:/etc/rabbitmq/definitions.json

  acc-database:
    container_name: accumulator-database
    image: mongo:3.4.19-jessie
    ports:
      - 27017:27017
    volumes:
      - ./data/acc-mongo:/data/db
      - ./assets:/home

  accumulator:
    container_name: accumulator
    build:
      context: ./accumulator
      dockerfile: Dockerfile
    environment:
      - STORE_HOST=acc-database
      - QUEUE_HOST=queue
      - QUEUE_USER=admin
      - QUEUE_PASSWORD=Admin@123
      - API_HOST=api
      - API_PORT=80
    restart: on-failure
    volumes:
      - ./accumulator/src:/usr/src/app/src
      - ./accumulator/@types:/usr/src/app/@types
    depends_on:
      - database
      - search-api
      - acc-database
      - queue
    links:
      - database
      - search-api
      - acc-database
      - queue
    command: bash -c "./wait-for-it.sh queue:5672 -t 80 -- echo \"RabbitMQ up\" && npm run tsc && ./node_modules/.bin/forever ./dist/index.js"
