FROM logstash:7.4.1

# Installing Logstash plugins
RUN logstash-plugin install logstash-filter-bytes
RUN logstash-plugin install logstash-filter-multiline
RUN logstash-plugin install logstash-filter-json_encode